
(in-package :ojts.gen)

(def-java-class "java.util.Collection")
(def-java-class "java.util.Collections")
(def-java-class "java.lang.Integer")
(def-java-class "java.lang.Double")
(def-java-class "java.lang.Boolean")
(def-java-class "java.lang.Byte")
(def-java-class "java.lang.Character")
(def-java-class "java.lang.Short")
(def-java-class "java.lang.Long")
(def-java-class "java.lang.Float")
(def-java-class "java.lang.Void")
(def-java-class "java.lang.Object")
(def-java-class "java.lang.String")
